services:
  server:
    build:
      context: ./server
    environment:
      GARNISH_ADDRESS: ":8080"
      GARNISH_CONFIG_PATH: "./"
  env:
    build:
      context: ./env
    command: env
    environment:
      KIMONO_ADDRESS: http://server:8080
      KIMONO_MANIFEST: env
      KIMONO_DEBUG: false
    depends_on:
      - server
